// Import&Export all HyperMD components except PowerPacks
// (This file is also used to generate all-in-one bundle)
//
// **DO NOT EDIT!** This file is generated by script.
//
// @see dev/HyperMD.config.js
//
define(["require", "exports", "./core", "./mode/hypermd", "./addon/insert-file", "./addon/read-link", "./addon/hover", "./addon/click", "./addon/paste", "./addon/fold", "./addon/fold-image", "./addon/fold-link", "./addon/fold-code", "./addon/fold-math", "./addon/fold-emoji", "./addon/fold-html", "./addon/table-align", "./addon/mode-loader", "./addon/hide-token", "./addon/cursor-debounce", "./keymap/hypermd"], function (require, exports, core_1, Mode, InsertFile, ReadLink, Hover, Click, Paste, Fold, FoldImage, FoldLink, FoldCode, FoldMath, FoldEmoji, FoldHTML, TableAlign, ModeLoader, HideToken, CursorDebounce, KeyMap) {
    "use strict";
    function __export(m) {
        for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
    }
    Object.defineProperty(exports, "__esModule", { value: true });
    __export(core_1);
    exports.Mode = Mode;
    exports.InsertFile = InsertFile;
    exports.ReadLink = ReadLink;
    exports.Hover = Hover;
    exports.Click = Click;
    exports.Paste = Paste;
    exports.Fold = Fold;
    exports.FoldImage = FoldImage;
    exports.FoldLink = FoldLink;
    exports.FoldCode = FoldCode;
    exports.FoldMath = FoldMath;
    exports.FoldEmoji = FoldEmoji;
    exports.FoldHTML = FoldHTML;
    exports.TableAlign = TableAlign;
    exports.ModeLoader = ModeLoader;
    exports.HideToken = HideToken;
    exports.CursorDebounce = CursorDebounce;
    exports.KeyMap = KeyMap;
});
